version: "3.9"
services:
  mongo:
    image: mongo:latest
    container_name: Mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27017:27017"
    volumes:
      - mongodemo:/data/db

volumes:
  mongodemo:
